name: Publish GitHub Actions Artifacts Example
on:
  push:
    branches: [ master ]
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          major-wording:  'major'
          minor-wording:  'feat'
          patch-wording:  'fix, build, ci, docs, perf, refactor, style'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: List of the GitHub Actions environment variables on Ubuntu
        run: env

      - name: List Github Sha
        run: |
          echo "$GITHUB_SHA"
          echo "echo ${GITHUB_SHA::7}"
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`"
